### ISSUE TITLE
Disable pasting and cutting when editor is readonly

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-clipboard#26]
When the editor is in read-only mode pasting should be disabled.
It would be nice to use a command to handle pasting. Commands are disabled by default in read-only mode.

**Comment by Reinmar** [comment]
The idea for the paste command is that it could do everything the pasting does. There may be special features listening for certain paste events and that command should work in such a way to trigger them all. But the problem is that the data transfer facade is passed to those events so we'd need to mock it.

If you don't want to risk spending too much time on this now I'd recommend skipping the command.

**Comment by oskarwrobel** [comment]
The same issue is for cutting.
